
TABLE_ID = 0
STEP_ID = 0
SWEEP_TABLE_VOLTAGE = 0
CB_MODE_VOLTAGE = 0

HK_PERIOD = 0
HK_ID = 0

IMAGE_INDEX = 0
FLASH_ADDR = 0x00000000
UPLOADING = False

SB_MODE_NR_STEPS = 0
SB_MODE_NR_SAMPLES_PER_STEP = 0
SB_MODE_NR_SKIPPED_SAMPLES = 0
SB_MODE_NR_SAMPLES_PER_POINT = 0
SB_MODE_NR_POINTS_PER_STEP = 0

APPLY_ON_ENTIRE_SWEEP_TABLE = 0

MACRO_SUBOP = 0x01